name = "UnitfulBase"
uuid = "66b8c3f9-6ee5-42bf-afc1-12298118d236"
version = "1.0.0"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ConstructionBase = "1"

julia = "1"
